### PR TITLE
Ahrs flashing

### PR DESCRIPTION
**Pull request by mikessut**
Here's where I ended up to get a working flash utility with my bootloader.  Hopefully, I didn't mangle your stuff too much.

I removed the timeout on line 119 to be able to consume the erroneous frames we talked about.  In the process, I refactored things a little bit (probably mainly because I was having trouble wrapping my head around the the try: else:).

### CODE REVIEW

**Comment by birkelbach** [comment]
Would this be a generally useful driver for STM32 uCs?

**Comment by mikessut** [comment]
I'm not sure how general it is to all of the different versions of the
STM32 with different flash layouts.  What do you have in mind?

**Comment by birkelbach** [comment]
I don't know that much about loading firmware into the STM32 but it would make sense that we have fewer drivers / bootloaders.  Kyle and I are working on some other STM32 based devices so if they could all share driver / bootloader code it would be helpful.

**Comment by mikessut** [comment]
Gotcha.  The only part that is specific to the part we're using is the
sector layout.

**Comment by birkelbach** [comment]
Cool.  I'm gonna merge these.  I'm a little worried that taking out the timeout will cause the driver to lock up if the node doesn't respond.  I think there is probably a better way to do that than all that mess that I had anyway, so we'll sort something out.

**Pull request merged**
